### ISSUE TITLE
pickle

### ISSUE THREAD

**Issue by mmalcorra** [mkreitmeir/limekiln#1]
Servus,

In auxiliaries.py there is no "pickle" file. Could you upload it please? It gives me an error:

" FileNotFoundError: [Errno 2] No such file or directory: '.\\pickle\\h_gas.pkl' "

I'm very interested in simulating different conditions of the PFR lime kiln. 

Thanks in advance.

**Comment by mkreitmeir** [comment]
The file can be generated with limekiln/auxilaries.py.
Best regards
